/* SPDX-License-Identifier: BSD-3-Clause */
/* Copyright (C) 2025 Microchip Technology Inc. and its subsidiaries.
 * Microchip VCAP API
 */

/* This file is autogenerated by cml-utils 2025-06-26 14:33:02 +0200.
 * Commit ID: 94897ab295c9b59282f07b148fda05aa3e329a68
 */

#ifndef __LAN9645X_VCAP_AG_API_H__
#define __LAN9645X_VCAP_AG_API_H__

#include "vcap_api.h"

/* VCAPs */
extern const struct vcap_info lan9645x_vcaps[];
extern const struct vcap_statistics lan9645x_vcap_stats;

#endif /* __LAN9645X_VCAP_AG_API_H__ */
