/* SPDX-License-Identifier: (GPL-2.0 OR MIT) */
/*
 * Microchip LAN966x Switch driver
 *
 * License: Dual MIT/GPL
 * Copyright (c) 2020 Microchip Technology Inc.
 */

/* This file is autogenerated by cml-utils 2021-02-04 13:07:36 +0100.
 * Commit ID: 0359c23857fee4dc44d5a77219b74b8cb979e0c1 (dirty)
 */

#ifndef _LAN966X_PCI_REGS_SR_H_
#define _LAN966X_PCI_REGS_SR_H_

#include <linux/bitops.h>

#define LAN966X_BUILD_ID_REG GCB_BUILDID
#define LAN966X_BUILD_ID 1610532836

enum lan966x_target {
	TARGET_CPU = 6,
	TARGET_GCB = 25,
	TARGET_ORG = 34,
	TARGET_SYS = 51,
	NUM_TARGETS = 65
};

#define __REG(...)    __VA_ARGS__

/*      CPU:INTR:INTR_TRIGGER */
#define CPU_INTR_TRIGGER(r)       __REG(TARGET_CPU,\
					0, 1, 288, 0, 1, 400, 12, r, 2, 4)

/*      CPU:INTR:INTR_TRIGGER1 */
#define CPU_INTR_TRIGGER1(r)      __REG(TARGET_CPU,\
					0, 1, 288, 0, 1, 400, 20, r, 2, 4)

/*      CPU:INTR:INTR_TRIGGER2 */
#define CPU_INTR_TRIGGER2(r)      __REG(TARGET_CPU,\
					0, 1, 288, 0, 1, 400, 28, r, 2, 4)

/*      CPU:INTR:INTR_STICKY */
#define CPU_INTR_STICKY           __REG(TARGET_CPU,\
					0, 1, 288, 0, 1, 400, 48, 0, 1, 4)

/*      CPU:INTR:INTR_STICKY1 */
#define CPU_INTR_STICKY1          __REG(TARGET_CPU,\
					0, 1, 288, 0, 1, 400, 52, 0, 1, 4)

/*      CPU:INTR:INTR_STICKY2 */
#define CPU_INTR_STICKY2          __REG(TARGET_CPU,\
					0, 1, 288, 0, 1, 400, 56, 0, 1, 4)

/*      CPU:INTR:INTR_ENA */
#define CPU_INTR_ENA              __REG(TARGET_CPU,\
					0, 1, 288, 0, 1, 400, 72, 0, 1, 4)

/*      CPU:INTR:INTR_ENA1 */
#define CPU_INTR_ENA1             __REG(TARGET_CPU,\
					0, 1, 288, 0, 1, 400, 76, 0, 1, 4)

/*      CPU:INTR:INTR_ENA2 */
#define CPU_INTR_ENA2             __REG(TARGET_CPU,\
					0, 1, 288, 0, 1, 400, 80, 0, 1, 4)

/*      CPU:INTR:INTR_ENA_CLR */
#define CPU_INTR_ENA_CLR          __REG(TARGET_CPU,\
					0, 1, 288, 0, 1, 400, 84, 0, 1, 4)

/*      CPU:INTR:INTR_ENA_CLR1 */
#define CPU_INTR_ENA_CLR1         __REG(TARGET_CPU,\
					0, 1, 288, 0, 1, 400, 88, 0, 1, 4)

/*      CPU:INTR:INTR_ENA_CLR2 */
#define CPU_INTR_ENA_CLR2         __REG(TARGET_CPU,\
					0, 1, 288, 0, 1, 400, 92, 0, 1, 4)

/*      CPU:INTR:INTR_ENA_SET */
#define CPU_INTR_ENA_SET          __REG(TARGET_CPU,\
					0, 1, 288, 0, 1, 400, 96, 0, 1, 4)

/*      CPU:INTR:INTR_ENA_SET1 */
#define CPU_INTR_ENA_SET1         __REG(TARGET_CPU,\
					0, 1, 288, 0, 1, 400, 100, 0, 1, 4)

/*      CPU:INTR:INTR_ENA_SET2 */
#define CPU_INTR_ENA_SET2         __REG(TARGET_CPU,\
					0, 1, 288, 0, 1, 400, 104, 0, 1, 4)

/*      CPU:INTR:DST_INTR_MAP */
#define CPU_DST_INTR_MAP(r)       __REG(TARGET_CPU,\
					0, 1, 288, 0, 1, 400, 120, r, 9, 4)

/*      CPU:INTR:DST_INTR_MAP1 */
#define CPU_DST_INTR_MAP1(r)      __REG(TARGET_CPU,\
					0, 1, 288, 0, 1, 400, 156, r, 9, 4)

/*      CPU:INTR:DST_INTR_MAP2 */
#define CPU_DST_INTR_MAP2(r)      __REG(TARGET_CPU,\
					0, 1, 288, 0, 1, 400, 192, r, 9, 4)

/*      CPU:INTR:DST_INTR_IDENT */
#define CPU_DST_INTR_IDENT(r)     __REG(TARGET_CPU,\
					0, 1, 288, 0, 1, 400, 228, r, 9, 4)

/*      CPU:INTR:DST_INTR_IDENT1 */
#define CPU_DST_INTR_IDENT1(r)    __REG(TARGET_CPU,\
					0, 1, 288, 0, 1, 400, 264, r, 9, 4)

/*      CPU:INTR:DST_INTR_IDENT2 */
#define CPU_DST_INTR_IDENT2(r)    __REG(TARGET_CPU,\
					0, 1, 288, 0, 1, 400, 300, r, 9, 4)

/*      CPU:INTR:DEV_INTR_TRIGGER */
#define CPU_DEV_INTR_TRIGGER(r)   __REG(TARGET_CPU,\
					0, 1, 288, 0, 1, 400, 356, r, 2, 4)

#define CPU_DEV_INTR_TRIGGER_DEV_INTR_TRIGGER(x) ((x) & GENMASK(7, 0))
#define CPU_DEV_INTR_TRIGGER_DEV_INTR_TRIGGER_M  GENMASK(7, 0)
#define CPU_DEV_INTR_TRIGGER_DEV_INTR_TRIGGER_X(x) ((x) & GENMASK(7, 0))

/*      CPU:INTR:DEV_INTR_STICKY */
#define CPU_DEV_INTR_STICKY       __REG(TARGET_CPU,\
					0, 1, 288, 0, 1, 400, 364, 0, 1, 4)

#define CPU_DEV_INTR_STICKY_DEV_INTR_STICKY(x)   ((x) & GENMASK(7, 0))
#define CPU_DEV_INTR_STICKY_DEV_INTR_STICKY_M    GENMASK(7, 0)
#define CPU_DEV_INTR_STICKY_DEV_INTR_STICKY_X(x) ((x) & GENMASK(7, 0))

/*      CPU:INTR:DEV_INTR_ENA */
#define CPU_DEV_INTR_ENA          __REG(TARGET_CPU,\
					0, 1, 288, 0, 1, 400, 372, 0, 1, 4)

#define CPU_DEV_INTR_ENA_DEV_INTR_ENA(x)         ((x) & GENMASK(7, 0))
#define CPU_DEV_INTR_ENA_DEV_INTR_ENA_M          GENMASK(7, 0)
#define CPU_DEV_INTR_ENA_DEV_INTR_ENA_X(x)       ((x) & GENMASK(7, 0))

/*      GCB:CHIP_REGS:SOFT_RST */
#define GCB_SOFT_RST              __REG(TARGET_GCB,\
					0, 1, 0, 0, 1, 68, 12, 0, 1, 4)

#define GCB_SOFT_RST_SOFT_SWC_RST(x)             (((x) << 1) & GENMASK(1, 1))
#define GCB_SOFT_RST_SOFT_SWC_RST_M              GENMASK(1, 1)
#define GCB_SOFT_RST_SOFT_SWC_RST_X(x)           (((x) & GENMASK(1, 1)) >> 1)

#define GCB_SOFT_RST_SOFT_CHIP_RST(x)            ((x) & GENMASK(0, 0))
#define GCB_SOFT_RST_SOFT_CHIP_RST_M             GENMASK(0, 0)
#define GCB_SOFT_RST_SOFT_CHIP_RST_X(x)          ((x) & GENMASK(0, 0))

/*      GCB:GPIO:GPIO_ALT */
#define GCB_GPIO_ALT(r)           __REG(TARGET_GCB,\
					0, 1, 100, 0, 1, 180, 96, r, 3, 4)

/*      GCB:GPIO:GPIO_ALT1 */
#define GCB_GPIO_ALT1(r)          __REG(TARGET_GCB,\
					0, 1, 100, 0, 1, 180, 108, r, 3, 4)

/*      GCB:GPIO:GPIO_ALT2 */
#define GCB_GPIO_ALT2(r)          __REG(TARGET_GCB,\
					0, 1, 100, 0, 1, 180, 120, r, 3, 4)

#define GCB_GPIO_ALT2_G_ALT2(x)                  ((x) & GENMASK(13, 0))
#define GCB_GPIO_ALT2_G_ALT2_M                   GENMASK(13, 0)
#define GCB_GPIO_ALT2_G_ALT2_X(x)                ((x) & GENMASK(13, 0))

/*      ORG:ORG:IF_CTRL */
#define ORG_IF_CTRL(t)            __REG(TARGET_ORG,\
					t, 2, 0, 0, 1, 72, 0, 0, 1, 4)

#define ORG_IF_CTRL_IF_CTRL(x)                   ((x) & GENMASK(3, 0))
#define ORG_IF_CTRL_IF_CTRL_M                    GENMASK(3, 0)
#define ORG_IF_CTRL_IF_CTRL_X(x)                 ((x) & GENMASK(3, 0))

/*      SYS:SYSTEM:RESET_CFG */
#define SYS_RESET_CFG             __REG(TARGET_SYS,\
					0, 1, 4128, 0, 1, 168, 0, 0, 1, 4)

#define SYS_RESET_CFG_CORE_ENA(x)                ((x) & GENMASK(0, 0))
#define SYS_RESET_CFG_CORE_ENA_M                 GENMASK(0, 0)
#define SYS_RESET_CFG_CORE_ENA_X(x)              ((x) & GENMASK(0, 0))

/*      SYS:RAM_CTRL:RAM_INIT */
#define SYS_RAM_INIT              __REG(TARGET_SYS,\
					0, 1, 4432, 0, 1, 4, 0, 0, 1, 4)

#define SYS_RAM_INIT_RAM_INIT(x)                 (((x) << 1) & GENMASK(1, 1))
#define SYS_RAM_INIT_RAM_INIT_M                  GENMASK(1, 1)
#define SYS_RAM_INIT_RAM_INIT_X(x)               (((x) & GENMASK(1, 1)) >> 1)

#define SYS_RAM_INIT_RAM_CFG_HOOK(x)             ((x) & GENMASK(0, 0))
#define SYS_RAM_INIT_RAM_CFG_HOOK_M              GENMASK(0, 0)
#define SYS_RAM_INIT_RAM_CFG_HOOK_X(x)           ((x) & GENMASK(0, 0))

#endif /* _LAN966X_PCI_REGS_SR_H_ */
