/* SPDX-License-Identifier: (GPL-2.0 OR MIT) */
/*
 * Microchip LAN966x Switch driver
 *
 * License: Dual MIT/GPL
 * Copyright (c) 2020 Microchip Technology Inc.
 */

/* This file is autogenerated by cml-utils 2021-02-04 13:07:26 +0100.
 * Commit ID: 0359c23857fee4dc44d5a77219b74b8cb979e0c1 (dirty)
 */

#ifndef _LAN966X_PCI_REGS_H_
#define _LAN966X_PCI_REGS_H_

#include <linux/bitops.h>

#define LAN966X_BUILD_ID_REG GCB_BUILDID
#define LAN966X_BUILD_ID 1610532836

enum lan966x_target {
	TARGET_GCB = 10,
	TARGET_ORG = 13,
	TARGET_SYS = 19,
	NUM_TARGETS = 23
};

#define __REG(...)    __VA_ARGS__

/*      GCB:CHIP_REGS:SOFT_RST */
#define GCB_SOFT_RST              __REG(TARGET_GCB,\
					0, 1, 0, 0, 1, 12, 4, 0, 1, 4)

#define GCB_SOFT_RST_SOFT_SWC_RST(x)             ((x) & GENMASK(0, 0))
#define GCB_SOFT_RST_SOFT_SWC_RST_M              GENMASK(0, 0)
#define GCB_SOFT_RST_SOFT_SWC_RST_X(x)           ((x) & GENMASK(0, 0))

/*      GCB:GPIO:GPIO_OUT */
#define GCB_GPIO_OUT(r)           __REG(TARGET_GCB,\
					0, 1, 12, 0, 1, 256, 64, r, 8, 4)

#define GCB_GPIO_OUT_G_OUT(x)                    ((x) & GENMASK(5, 0))
#define GCB_GPIO_OUT_G_OUT_M                     GENMASK(5, 0)
#define GCB_GPIO_OUT_G_OUT_X(x)                  ((x) & GENMASK(5, 0))

/*      ORG:ORG:IF_CTRL */
#define ORG_IF_CTRL               __REG(TARGET_ORG,\
					0, 1, 0, 0, 1, 72, 0, 0, 1, 4)

#define ORG_IF_CTRL_IF_CTRL(x)                   ((x) & GENMASK(3, 0))
#define ORG_IF_CTRL_IF_CTRL_M                    GENMASK(3, 0)
#define ORG_IF_CTRL_IF_CTRL_X(x)                 ((x) & GENMASK(3, 0))

/*      SYS:SYSTEM:RESET_CFG */
#define SYS_RESET_CFG             __REG(TARGET_SYS,\
					0, 1, 4128, 0, 1, 168, 0, 0, 1, 4)

#define SYS_RESET_CFG_CORE_ENA(x)                ((x) & GENMASK(0, 0))
#define SYS_RESET_CFG_CORE_ENA_M                 GENMASK(0, 0)
#define SYS_RESET_CFG_CORE_ENA_X(x)              ((x) & GENMASK(0, 0))

/*      SYS:RAM_CTRL:RAM_INIT */
#define SYS_RAM_INIT              __REG(TARGET_SYS,\
					0, 1, 4432, 0, 1, 4, 0, 0, 1, 4)

#define SYS_RAM_INIT_RAM_INIT(x)                 (((x) << 1) & GENMASK(1, 1))
#define SYS_RAM_INIT_RAM_INIT_M                  GENMASK(1, 1)
#define SYS_RAM_INIT_RAM_INIT_X(x)               (((x) & GENMASK(1, 1)) >> 1)

#define SYS_RAM_INIT_RAM_CFG_HOOK(x)             ((x) & GENMASK(0, 0))
#define SYS_RAM_INIT_RAM_CFG_HOOK_M              GENMASK(0, 0)
#define SYS_RAM_INIT_RAM_CFG_HOOK_X(x)           ((x) & GENMASK(0, 0))

#endif /* _LAN966X_PCI_REGS_H_ */
