/* SPDX-License-Identifier: GPL-2.0-or-later */

#ifndef _LAN9645X_SERDES_REGS_H_
#define _LAN9645X_SERDES_REGS_H_

#include <linux/bitfield.h>
#include <linux/types.h>
#include <linux/bug.h>

/* HSIO:SD:SD_CFG */
#define HSIO_SD_CFG_PHY_RESET                    BIT(27)
#define HSIO_SD_CFG_PHY_RESET_SET(x)\
	FIELD_PREP(HSIO_SD_CFG_PHY_RESET, x)
#define HSIO_SD_CFG_PHY_RESET_GET(x)\
	FIELD_GET(HSIO_SD_CFG_PHY_RESET, x)

#define HSIO_SD_CFG_TX_RESET                     BIT(18)
#define HSIO_SD_CFG_TX_RESET_SET(x)\
	FIELD_PREP(HSIO_SD_CFG_TX_RESET, x)
#define HSIO_SD_CFG_TX_RESET_GET(x)\
	FIELD_GET(HSIO_SD_CFG_TX_RESET, x)

#define HSIO_SD_CFG_TX_RATE                      GENMASK(17, 16)
#define HSIO_SD_CFG_TX_RATE_SET(x)\
	FIELD_PREP(HSIO_SD_CFG_TX_RATE, x)
#define HSIO_SD_CFG_TX_RATE_GET(x)\
	FIELD_GET(HSIO_SD_CFG_TX_RATE, x)

#define HSIO_SD_CFG_TX_INVERT                    BIT(15)
#define HSIO_SD_CFG_TX_INVERT_SET(x)\
	FIELD_PREP(HSIO_SD_CFG_TX_INVERT, x)
#define HSIO_SD_CFG_TX_INVERT_GET(x)\
	FIELD_GET(HSIO_SD_CFG_TX_INVERT, x)

#define HSIO_SD_CFG_TX_EN                        BIT(14)
#define HSIO_SD_CFG_TX_EN_SET(x)\
	FIELD_PREP(HSIO_SD_CFG_TX_EN, x)
#define HSIO_SD_CFG_TX_EN_GET(x)\
	FIELD_GET(HSIO_SD_CFG_TX_EN, x)

#define HSIO_SD_CFG_TX_DATA_EN                   BIT(12)
#define HSIO_SD_CFG_TX_DATA_EN_SET(x)\
	FIELD_PREP(HSIO_SD_CFG_TX_DATA_EN, x)
#define HSIO_SD_CFG_TX_DATA_EN_GET(x)\
	FIELD_GET(HSIO_SD_CFG_TX_DATA_EN, x)

#define HSIO_SD_CFG_TX_CM_EN                     BIT(11)
#define HSIO_SD_CFG_TX_CM_EN_SET(x)\
	FIELD_PREP(HSIO_SD_CFG_TX_CM_EN, x)
#define HSIO_SD_CFG_TX_CM_EN_GET(x)\
	FIELD_GET(HSIO_SD_CFG_TX_CM_EN, x)

#define HSIO_SD_CFG_LANE_10BIT_SEL               BIT(10)
#define HSIO_SD_CFG_LANE_10BIT_SEL_SET(x)\
	FIELD_PREP(HSIO_SD_CFG_LANE_10BIT_SEL, x)
#define HSIO_SD_CFG_LANE_10BIT_SEL_GET(x)\
	FIELD_GET(HSIO_SD_CFG_LANE_10BIT_SEL, x)

#define HSIO_SD_CFG_RX_TERM_EN                   BIT(9)
#define HSIO_SD_CFG_RX_TERM_EN_SET(x)\
	FIELD_PREP(HSIO_SD_CFG_RX_TERM_EN, x)
#define HSIO_SD_CFG_RX_TERM_EN_GET(x)\
	FIELD_GET(HSIO_SD_CFG_RX_TERM_EN, x)

#define HSIO_SD_CFG_RX_RESET                     BIT(8)
#define HSIO_SD_CFG_RX_RESET_SET(x)\
	FIELD_PREP(HSIO_SD_CFG_RX_RESET, x)
#define HSIO_SD_CFG_RX_RESET_GET(x)\
	FIELD_GET(HSIO_SD_CFG_RX_RESET, x)

#define HSIO_SD_CFG_RX_RATE                      GENMASK(7, 6)
#define HSIO_SD_CFG_RX_RATE_SET(x)\
	FIELD_PREP(HSIO_SD_CFG_RX_RATE, x)
#define HSIO_SD_CFG_RX_RATE_GET(x)\
	FIELD_GET(HSIO_SD_CFG_RX_RATE, x)

#define HSIO_SD_CFG_RX_PLL_EN                    BIT(5)
#define HSIO_SD_CFG_RX_PLL_EN_SET(x)\
	FIELD_PREP(HSIO_SD_CFG_RX_PLL_EN, x)
#define HSIO_SD_CFG_RX_PLL_EN_GET(x)\
	FIELD_GET(HSIO_SD_CFG_RX_PLL_EN, x)

#define HSIO_SD_CFG_RX_INVERT                    BIT(3)
#define HSIO_SD_CFG_RX_INVERT_SET(x)\
	FIELD_PREP(HSIO_SD_CFG_RX_INVERT, x)
#define HSIO_SD_CFG_RX_INVERT_GET(x)\
	FIELD_GET(HSIO_SD_CFG_RX_INVERT, x)

#define HSIO_SD_CFG_RX_DATA_EN                   BIT(2)
#define HSIO_SD_CFG_RX_DATA_EN_SET(x)\
	FIELD_PREP(HSIO_SD_CFG_RX_DATA_EN, x)
#define HSIO_SD_CFG_RX_DATA_EN_GET(x)\
	FIELD_GET(HSIO_SD_CFG_RX_DATA_EN, x)

#define HSIO_SD_CFG_LANE_LOOPBK_EN               BIT(0)
#define HSIO_SD_CFG_LANE_LOOPBK_EN_SET(x)\
	FIELD_PREP(HSIO_SD_CFG_LANE_LOOPBK_EN, x)
#define HSIO_SD_CFG_LANE_LOOPBK_EN_GET(x)\
	FIELD_GET(HSIO_SD_CFG_LANE_LOOPBK_EN, x)

/* HSIO:SD:MPLL_CFG */
#define HSIO_MPLL_CFG_REF_SSP_EN                 BIT(18)
#define HSIO_MPLL_CFG_REF_SSP_EN_SET(x)\
	FIELD_PREP(HSIO_MPLL_CFG_REF_SSP_EN, x)
#define HSIO_MPLL_CFG_REF_SSP_EN_GET(x)\
	FIELD_GET(HSIO_MPLL_CFG_REF_SSP_EN, x)

#define HSIO_MPLL_CFG_REF_CLKDIV2                BIT(17)
#define HSIO_MPLL_CFG_REF_CLKDIV2_SET(x)\
	FIELD_PREP(HSIO_MPLL_CFG_REF_CLKDIV2, x)
#define HSIO_MPLL_CFG_REF_CLKDIV2_GET(x)\
	FIELD_GET(HSIO_MPLL_CFG_REF_CLKDIV2, x)

#define HSIO_MPLL_CFG_MPLL_EN                    BIT(16)
#define HSIO_MPLL_CFG_MPLL_EN_SET(x)\
	FIELD_PREP(HSIO_MPLL_CFG_MPLL_EN, x)
#define HSIO_MPLL_CFG_MPLL_EN_GET(x)\
	FIELD_GET(HSIO_MPLL_CFG_MPLL_EN, x)

#define HSIO_MPLL_CFG_MPLL_MULTIPLIER            GENMASK(6, 0)
#define HSIO_MPLL_CFG_MPLL_MULTIPLIER_SET(x)\
	FIELD_PREP(HSIO_MPLL_CFG_MPLL_MULTIPLIER, x)
#define HSIO_MPLL_CFG_MPLL_MULTIPLIER_GET(x)\
	FIELD_GET(HSIO_MPLL_CFG_MPLL_MULTIPLIER, x)

/* HSIO:SD:SD_STAT */
#define HSIO_SD_STAT_MPLL_STATE                  BIT(6)
#define HSIO_SD_STAT_MPLL_STATE_SET(x)\
	FIELD_PREP(HSIO_SD_STAT_MPLL_STATE, x)
#define HSIO_SD_STAT_MPLL_STATE_GET(x)\
	FIELD_GET(HSIO_SD_STAT_MPLL_STATE, x)

#define HSIO_SD_STAT_TX_STATE                    BIT(5)
#define HSIO_SD_STAT_TX_STATE_SET(x)\
	FIELD_PREP(HSIO_SD_STAT_TX_STATE, x)
#define HSIO_SD_STAT_TX_STATE_GET(x)\
	FIELD_GET(HSIO_SD_STAT_TX_STATE, x)

#define HSIO_SD_STAT_TX_CM_STATE                 BIT(2)
#define HSIO_SD_STAT_TX_CM_STATE_SET(x)\
	FIELD_PREP(HSIO_SD_STAT_TX_CM_STATE, x)
#define HSIO_SD_STAT_TX_CM_STATE_GET(x)\
	FIELD_GET(HSIO_SD_STAT_TX_CM_STATE, x)

#define HSIO_SD_STAT_RX_PLL_STATE                BIT(0)
#define HSIO_SD_STAT_RX_PLL_STATE_SET(x)\
	FIELD_PREP(HSIO_SD_STAT_RX_PLL_STATE, x)
#define HSIO_SD_STAT_RX_PLL_STATE_GET(x)\
	FIELD_GET(HSIO_SD_STAT_RX_PLL_STATE, x)

/* HSIO:HW_CFGSTAT:RGMII_CFG */
#define HSIO_RGMII_CFG_IB_RX_LINK_STATUS         BIT(15)
#define HSIO_RGMII_CFG_IB_RX_LINK_STATUS_SET(x)\
	FIELD_PREP(HSIO_RGMII_CFG_IB_RX_LINK_STATUS, x)
#define HSIO_RGMII_CFG_IB_RX_LINK_STATUS_GET(x)\
	FIELD_GET(HSIO_RGMII_CFG_IB_RX_LINK_STATUS, x)

#define HSIO_RGMII_CFG_IB_RX_DUPLEX              BIT(14)
#define HSIO_RGMII_CFG_IB_RX_DUPLEX_SET(x)\
	FIELD_PREP(HSIO_RGMII_CFG_IB_RX_DUPLEX, x)
#define HSIO_RGMII_CFG_IB_RX_DUPLEX_GET(x)\
	FIELD_GET(HSIO_RGMII_CFG_IB_RX_DUPLEX, x)

#define HSIO_RGMII_CFG_IB_RX_SPEED               GENMASK(13, 12)
#define HSIO_RGMII_CFG_IB_RX_SPEED_SET(x)\
	FIELD_PREP(HSIO_RGMII_CFG_IB_RX_SPEED, x)
#define HSIO_RGMII_CFG_IB_RX_SPEED_GET(x)\
	FIELD_GET(HSIO_RGMII_CFG_IB_RX_SPEED, x)

#define HSIO_RGMII_CFG_IB_TX_LINK_STATUS         BIT(11)
#define HSIO_RGMII_CFG_IB_TX_LINK_STATUS_SET(x)\
	FIELD_PREP(HSIO_RGMII_CFG_IB_TX_LINK_STATUS, x)
#define HSIO_RGMII_CFG_IB_TX_LINK_STATUS_GET(x)\
	FIELD_GET(HSIO_RGMII_CFG_IB_TX_LINK_STATUS, x)

#define HSIO_RGMII_CFG_IB_TX_FDX                 BIT(10)
#define HSIO_RGMII_CFG_IB_TX_FDX_SET(x)\
	FIELD_PREP(HSIO_RGMII_CFG_IB_TX_FDX, x)
#define HSIO_RGMII_CFG_IB_TX_FDX_GET(x)\
	FIELD_GET(HSIO_RGMII_CFG_IB_TX_FDX, x)

#define HSIO_RGMII_CFG_IB_TX_MII_SPD             BIT(9)
#define HSIO_RGMII_CFG_IB_TX_MII_SPD_SET(x)\
	FIELD_PREP(HSIO_RGMII_CFG_IB_TX_MII_SPD, x)
#define HSIO_RGMII_CFG_IB_TX_MII_SPD_GET(x)\
	FIELD_GET(HSIO_RGMII_CFG_IB_TX_MII_SPD, x)

#define HSIO_RGMII_CFG_IB_TX_SPD_1G              BIT(8)
#define HSIO_RGMII_CFG_IB_TX_SPD_1G_SET(x)\
	FIELD_PREP(HSIO_RGMII_CFG_IB_TX_SPD_1G, x)
#define HSIO_RGMII_CFG_IB_TX_SPD_1G_GET(x)\
	FIELD_GET(HSIO_RGMII_CFG_IB_TX_SPD_1G, x)

#define HSIO_RGMII_CFG_IB_TX_ENA                 BIT(7)
#define HSIO_RGMII_CFG_IB_TX_ENA_SET(x)\
	FIELD_PREP(HSIO_RGMII_CFG_IB_TX_ENA, x)
#define HSIO_RGMII_CFG_IB_TX_ENA_GET(x)\
	FIELD_GET(HSIO_RGMII_CFG_IB_TX_ENA, x)

#define HSIO_RGMII_CFG_IB_RX_ENA                 BIT(6)
#define HSIO_RGMII_CFG_IB_RX_ENA_SET(x)\
	FIELD_PREP(HSIO_RGMII_CFG_IB_RX_ENA, x)
#define HSIO_RGMII_CFG_IB_RX_ENA_GET(x)\
	FIELD_GET(HSIO_RGMII_CFG_IB_RX_ENA, x)

#define HSIO_RGMII_CFG_IB_ENA                    BIT(5)
#define HSIO_RGMII_CFG_IB_ENA_SET(x)\
	FIELD_PREP(HSIO_RGMII_CFG_IB_ENA, x)
#define HSIO_RGMII_CFG_IB_ENA_GET(x)\
	FIELD_GET(HSIO_RGMII_CFG_IB_ENA, x)

#define HSIO_RGMII_CFG_TX_CLK_CFG                GENMASK(4, 2)
#define HSIO_RGMII_CFG_TX_CLK_CFG_SET(x)\
	FIELD_PREP(HSIO_RGMII_CFG_TX_CLK_CFG, x)
#define HSIO_RGMII_CFG_TX_CLK_CFG_GET(x)\
	FIELD_GET(HSIO_RGMII_CFG_TX_CLK_CFG, x)

#define HSIO_RGMII_CFG_RGMII_TX_RST              BIT(1)
#define HSIO_RGMII_CFG_RGMII_TX_RST_SET(x)\
	FIELD_PREP(HSIO_RGMII_CFG_RGMII_TX_RST, x)
#define HSIO_RGMII_CFG_RGMII_TX_RST_GET(x)\
	FIELD_GET(HSIO_RGMII_CFG_RGMII_TX_RST, x)

#define HSIO_RGMII_CFG_RGMII_RX_RST              BIT(0)
#define HSIO_RGMII_CFG_RGMII_RX_RST_SET(x)\
	FIELD_PREP(HSIO_RGMII_CFG_RGMII_RX_RST, x)
#define HSIO_RGMII_CFG_RGMII_RX_RST_GET(x)\
	FIELD_GET(HSIO_RGMII_CFG_RGMII_RX_RST, x)

/* HSIO:HW_CFGSTAT:DLL_CFG */
#define HSIO_DLL_CFG_DLL_CLK_ENA                 BIT(20)
#define HSIO_DLL_CFG_DLL_CLK_ENA_SET(x)\
	FIELD_PREP(HSIO_DLL_CFG_DLL_CLK_ENA, x)
#define HSIO_DLL_CFG_DLL_CLK_ENA_GET(x)\
	FIELD_GET(HSIO_DLL_CFG_DLL_CLK_ENA, x)

#define HSIO_DLL_CFG_BIST_PASS                   BIT(19)
#define HSIO_DLL_CFG_BIST_PASS_SET(x)\
	FIELD_PREP(HSIO_DLL_CFG_BIST_PASS, x)
#define HSIO_DLL_CFG_BIST_PASS_GET(x)\
	FIELD_GET(HSIO_DLL_CFG_BIST_PASS, x)

#define HSIO_DLL_CFG_BIST_END                    BIT(18)
#define HSIO_DLL_CFG_BIST_END_SET(x)\
	FIELD_PREP(HSIO_DLL_CFG_BIST_END, x)
#define HSIO_DLL_CFG_BIST_END_GET(x)\
	FIELD_GET(HSIO_DLL_CFG_BIST_END, x)

#define HSIO_DLL_CFG_BIST_START                  BIT(17)
#define HSIO_DLL_CFG_BIST_START_SET(x)\
	FIELD_PREP(HSIO_DLL_CFG_BIST_START, x)
#define HSIO_DLL_CFG_BIST_START_GET(x)\
	FIELD_GET(HSIO_DLL_CFG_BIST_START, x)

#define HSIO_DLL_CFG_TAP_SEL                     GENMASK(16, 10)
#define HSIO_DLL_CFG_TAP_SEL_SET(x)\
	FIELD_PREP(HSIO_DLL_CFG_TAP_SEL, x)
#define HSIO_DLL_CFG_TAP_SEL_GET(x)\
	FIELD_GET(HSIO_DLL_CFG_TAP_SEL, x)

#define HSIO_DLL_CFG_TAP_ADJ                     GENMASK(9, 3)
#define HSIO_DLL_CFG_TAP_ADJ_SET(x)\
	FIELD_PREP(HSIO_DLL_CFG_TAP_ADJ, x)
#define HSIO_DLL_CFG_TAP_ADJ_GET(x)\
	FIELD_GET(HSIO_DLL_CFG_TAP_ADJ, x)

#define HSIO_DLL_CFG_DELAY_ENA                   BIT(2)
#define HSIO_DLL_CFG_DELAY_ENA_SET(x)\
	FIELD_PREP(HSIO_DLL_CFG_DELAY_ENA, x)
#define HSIO_DLL_CFG_DELAY_ENA_GET(x)\
	FIELD_GET(HSIO_DLL_CFG_DELAY_ENA, x)

#define HSIO_DLL_CFG_DLL_ENA                     BIT(1)
#define HSIO_DLL_CFG_DLL_ENA_SET(x)\
	FIELD_PREP(HSIO_DLL_CFG_DLL_ENA, x)
#define HSIO_DLL_CFG_DLL_ENA_GET(x)\
	FIELD_GET(HSIO_DLL_CFG_DLL_ENA, x)

#define HSIO_DLL_CFG_DLL_RST                     BIT(0)
#define HSIO_DLL_CFG_DLL_RST_SET(x)\
	FIELD_PREP(HSIO_DLL_CFG_DLL_RST, x)
#define HSIO_DLL_CFG_DLL_RST_GET(x)\
	FIELD_GET(HSIO_DLL_CFG_DLL_RST, x)

#endif /* _LAN9645X_HSIO_REGS_H_ */
